import { inter, lato, roboto } from '@/fonts/fonts';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import '@/styles/main/main.scss';
import { Header } from '@/components/common/Header/Header';
import { DashboardSidebar } from '@/components/common/DashboardSidebar/DashboardSidebar ';

export const metadata: Metadata = {
  title: 'Bank Dashboard',
  description: 'Generated by create next app',
  icons: '/favicon/dashboard.svg',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${roboto.className} ${lato.className}`}
      >
        <Header />
        <main className="main">
          <DashboardSidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
